ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"   
drosera_rpc = "https://relay.hoodi.drosera.io"
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D" 

[traps] 

[traps.ciltrap]
path = "out/CILTRAP.sol/CILTrap.json"
response_contract = "0x7919Ca40B3F38791fe61Dc864f633a93478b2810"
response_function = "transferFrom(address,address,uint256)"
cooldown_period_blocks = 8
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 2
private_trap = true
whitelist = ["0x66198DFc996929f0d499e273EfD32F71430F8F92"]
address = "0x6443fc44a9fe85fdff4dd2cf563b99151c3cfe85"
